services:
  reverse-proxy:
    # Das offizielle v3 Traefik Docker-Image
    image: traefik:v3.2
    command:
      # Experimentell, um das Dashboard ohne Zugriffsschutz aufzurufen
      #- "--api.insecure=true"
      - "--providers.docker"
      # wir selbst dürfen entscheiden welche container von Traefik erkannt werden
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik_web"
      # Traefik Einstiegspunkt
      - "--entrypoints.http.address=:80"
      # Traefik Einstiegspunkt Weiterleitung von http to https
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https.address=:443"
      # Vermeidet, dass wir den resolver in jedem container mit "traefik.http.routers.https.tls.certresolver=le" angeben muessen
      - "--entrypoints.https.http.tls.certResolver=le"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=andrey.boiv@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      # Ports für Traefik Dashboard
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
      - ./traefik_logs:/log
    networks:
      - web

networks:
  web:
    name: traefik_web