FROM nginx:1.27.2-alpine3.20
COPY ./dist/onboarding-frontend/browser /usr/share/nginx/html
EXPOSE 80

#FROM node:22-alpine3.20
#WORKDIR /app
#EXPOSE 4200
#COPY package.json ./
#RUN npm install
#COPY . .
#CMD ["npm","run"]
